using UnityEditor;
using UnityEditor.Build;
using UnityEditor.Build.Reporting;
using System;
using System.IO;

/// <summary>
/// Rewrites Assets/Scripts/Core/BuildInfo.cs with the current version and timestamp
/// whenever you enter Play Mode or trigger a build.
/// </summary>
[InitializeOnLoad]
public class BuildInfoUpdater : IPreprocessBuildWithReport
{
    public int callbackOrder => 0;

    static BuildInfoUpdater()
    {
        EditorApplication.playModeStateChanged += state =>
        {
            if (state == PlayModeStateChange.ExitingEditMode)
                Write();
        };
    }

    public void OnPreprocessBuild(BuildReport _) => Write();

    static void Write()
    {
        string version   = PlayerSettings.bundleVersion;
        string timestamp = DateTime.Now.ToString("yyyy-MM-dd  HH:mm");
        string path      = "Assets/Scripts/Core/BuildInfo.cs";

        string content =
$@"/// <summary>
/// Auto-generated by BuildInfoUpdater — do not edit manually.
/// Rewritten each time you enter Play Mode or make a build.
/// </summary>
public static class BuildInfo
{{
    public const string Version   = ""{version}"";
    public const string BuildTime = ""{timestamp}"";
}}
";
        File.WriteAllText(path, content);
        AssetDatabase.ImportAsset(path);
    }
}
