/// <summary>
/// Auto-generated by BuildInfoUpdater — do not edit manually.
/// Rewritten each time you enter Play Mode or make a build.
/// </summary>
public static class BuildInfo
{
    public const string Version   = "0.1.0";
    public const string BuildTime = "–";
}
